<tr>
    <td height=9 background=<?php echo SKIN_PATH ?>default/images/bg-footer.gif></td>
</tr>
<tr>
    <td align=center class="footer"><a href="#">Trang chủ</a>&nbsp;&nbsp; |&nbsp;&nbsp; <a href="#">Giới thiệu</a>&nbsp;&nbsp; |&nbsp;&nbsp; 
    <a href"#">Dịch vụ</a>&nbsp;&nbsp; |&nbsp;&nbsp; 
    <a href"#">Tin tức</a>&nbsp;&nbsp; |&nbsp;&nbsp; 
    <a href="#">Liên hệ</a>&nbsp;&nbsp; |&nbsp;&nbsp; <a href="#">Bảng giá</a>
    <img src=<?php echo SKIN_PATH ?>default/images/line-footer.gif style="margin: 5px 0px 10px 0px;"><br>
    Send mail to hoinongdanninhbinh@yahoo.com.vn with questions or comments.<br>
    Copyright © 2014 by Hoi Nong Dan Ninh Binh. All rights reserved. </td>
</tr>
    <?php //echo $footer;?>