<div class="top_header">
    <div class="div_header"></div>
    <div class="clr"></div>
    <div class="top_content">
        <!-- Main menu -->
        <div class="fl"><a href="/"><img src="<?php echo SKIN_PATH ?>default/plugins/dropmenu/images/home_ico.png" /></a></div>
        <div class="nav fl">  
            <?php echo $menuHtml;?>           
        </div>
        <div class="hotline">            
            Hotline:  <?php echo $hotline;?>             
        </div>
        <div class="clr"></div>
        <!-- End Main menu -->
    </div>
</div>