<!-- START SLIDER -->
<script type="text/javascript" src="<?php echo SKIN_PATH?>default/plugins/revolslider/js/jquery_003.js"></script>
<script type="text/javascript" src="<?php echo SKIN_PATH?>default/plugins/revolslider/js/jquery-migrate.js"></script>
<script type="text/javascript" src="<?php echo SKIN_PATH?>default/plugins/revolslider/js/jquery.js"></script>
<script type="text/javascript" src="<?php echo SKIN_PATH?>default/plugins/revolslider/js/jquery_009.js"></script>

<link rel="stylesheet" id="rev-google-font" href="<?php echo SKIN_PATH?>default/plugins/revolslider/css/revolslider.css" type="text/css" media="all">
<link rel="stylesheet" id="rs-settings-css" href="<?php echo SKIN_PATH?>default/plugins/revolslider/css/settings.css" type="text/css" media="all">
<link rel="stylesheet" id="rs-settings-css" href="<?php echo SKIN_PATH?>default/plugins/revolslider/css/captions.css" type="text/css" media="all">

<div id="subhead_full">
<div id="rev_slider_1_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" style="margin:0px auto;background-color:#f5f5f5;padding:0px;margin-top:0px;margin-bottom:0px;max-height:430px;">
    <div id="rev_slider_1_1" class="rev_slider fullwidthabanner tp-simpleresponsive hovered" style="max-height: 430px; height: 711px;">						
        <ul style="display: block;">
            <li style="visibility: visible; left: 0px; top: 0px; z-index: 20; opacity: 1;" data-transition="3dcurtain-vertical" data-slotamount="7">
                <div class="slotholder"><img style="width: 1601.16px; height: 430px; position: absolute; left: -7px; top: 0px; opacity: 1;" class="defaultimg" src="<?php echo SKIN_PATH?>default/plugins/revolslider/images/1_bg-1024x275.png" alt="1_bg-1024x275" data-fullwidthcentering="true"></div>

                <div style="font-size: 40px; padding: 0px; margin: 0px; border-width: 0px; border-style: none; border-color: -moz-use-text-color; line-height: 40px; white-space: nowrap; opacity: 1; left: 345.5px; top: 21px; transform: scale(1, 1) rotate(0deg); visibility: visible;" class="tp-caption large_text sfb start" data-x="32" data-y="21" data-speed="300" data-start="800" data-easing="easeOutExpo">WEBSITE <span style="color:#ffcc00;">TẤT CẢ MỌI NGƯỜI</span> ĐỀU THÍCH</div>

                <div style="left: 369.5px; top: 114px; opacity: 1; transform: scale(1, 1) rotate(0deg) translate(0px, 0px); visibility: visible;" class="tp-caption randomrotate start" data-x="56" data-y="114" data-speed="600" data-start="1200" data-easing="easeOutExpo"><img style="width: 140px; height: 140px;" src="<?php echo SKIN_PATH?>default/plugins/revolslider/images/5.png" alt="Thiết kế web Trí Tuệ Việt_Image 8"></div>

                <div style="left: 420.5px; top: 159px; opacity: 1; transform: scale(1, 1) rotate(0deg) translate(0px, 0px); visibility: visible;" class="tp-caption randomrotate start" data-x="107" data-y="159" data-speed="600" data-start="1300" data-easing="easeOutExpo"><img style="width: 140px; height: 140px;" src="<?php echo SKIN_PATH?>default/plugins/revolslider/images/3.png" alt="Thiết kế web Trí Tuệ Việt_Image 3"></div>

                <div style="left: 550.5px; top: 107px; opacity: 1; transform: scale(1, 1) rotate(0deg) translate(0px, 0px); visibility: visible;" class="tp-caption randomrotate start" data-x="237" data-y="107" data-speed="600" data-start="1400" data-easing="easeOutExpo"><img style="width: 140px; height: 140px;" src="<?php echo SKIN_PATH?>default/plugins/revolslider/images/4.png" alt="Thiết kế web Trí Tuệ Việt_Image 4"></div>

                <div style="left: 498.5px; top: 157px; opacity: 1; transform: scale(1, 1) rotate(0deg) translate(0px, 0px); visibility: visible;" class="tp-caption randomrotate start" data-x="185" data-y="157" data-speed="600" data-start="1500" data-easing="easeOutExpo"><img style="width: 140px; height: 140px;" src="<?php echo SKIN_PATH?>default/plugins/revolslider/images/6.png" alt="Thiết kế web Trí Tuệ Việt_Image 5"></div>

                <div style="left: 374.5px; top: 240px; opacity: 1; transform: scale(1, 1) rotate(0deg) translate(0px, 0px); visibility: visible;" class="tp-caption randomrotate start" data-x="61" data-y="240" data-speed="60" data-start="1600" data-easing="easeOutExpo"><img style="width: 140px; height: 140px;" src="<?php echo SKIN_PATH?>default/plugins/revolslider/images/1.png" alt="Thiết kế web Trí Tuệ Việt_Image 6"></div>

                <div style="left: 489.5px; top: 257px; opacity: 1; transform: scale(1, 1) rotate(0deg) translate(0px, 0px); visibility: visible;" class="tp-caption randomrotate start" data-x="176" data-y="257" data-speed="600" data-start="1700" data-easing="easeOutExpo"><img style="width: 140px; height: 140px;" src="<?php echo SKIN_PATH?>default/plugins/revolslider/images/7.png" alt="Thiết kế web Trí Tuệ Việt_Image 7"></div>

                <div style="left: 460.5px; top: 190px; opacity: 1; transform: scale(1, 1) rotate(0deg) translate(0px, 0px); visibility: visible;" class="tp-caption randomrotate start" data-x="147" data-y="190" data-speed="600" data-start="1800" data-easing="easeOutExpo"><img style="width: 140px; height: 140px;" src="<?php echo SKIN_PATH?>default/plugins/revolslider/images/2.png" alt="Thiết kế web Trí Tuệ Việt_Image 8"></div>

                <div style="left: 565.5px; top: 201px; opacity: 1; transform: scale(1, 1) rotate(0deg) translate(0px, 0px); visibility: visible;" class="tp-caption randomrotate start" data-x="252" data-y="201" data-speed="600" data-start="1900" data-easing="easeOutExpo"><img style="width: 140px; height: 140px;" src="<?php echo SKIN_PATH?>default/plugins/revolslider/images/8.png" alt="Thiết kế web Trí Tuệ Việt_Image 9"></div>

                <div style="left: 446.5px; top: 91px; opacity: 1; transform: scale(1, 1) rotate(0deg) translate(0px, 0px); visibility: visible;" class="tp-caption randomrotate start" data-x="133" data-y="91" data-speed="600" data-start="2000" data-easing="easeOutExpo"><img style="width: 140px; height: 140px;" src="<?php echo SKIN_PATH?>default/plugins/revolslider/images/9.png" alt="Thiết kế web Trí Tuệ Việt_Image 10"></div>

                <div style="left: 345.5px; top: 156px; opacity: 1; transform: scale(1, 1) rotate(0deg) translate(0px, 0px); visibility: visible;" class="tp-caption randomrotate start" data-x="32" data-y="156" data-speed="600" data-start="2100" data-easing="easeOutExpo"><img style="width: 140px; height: 140px;" src="<?php echo SKIN_PATH?>default/plugins/revolslider/images/10.png" alt="Thiết kế web Trí Tuệ Việt_Image 11"></div>

                <div style="opacity: 1; left: 785.5px; top: 83px; transform: scale(1, 1) rotate(0deg); visibility: visible;" class="tp-caption lfr start" data-x="472" data-y="83" data-speed="500" data-start="700" data-easing="easeOutExpo"><img style="width: 517px; height: 348px;" src="<?php echo SKIN_PATH?>default/plugins/revolslider/images/man.png" alt="Thiết kế web Trí Tuệ Việt_Image 12"></div>
            </li>
            <li data-transition="fade" data-slotamount="7" data-delay="9600">
                <div class="slotholder"><img style="width: 1601.16px; height: 430px; position: absolute; left: -7px; top: 0px; opacity: 0;" class="defaultimg" src="<?php echo SKIN_PATH?>default/plugins/revolslider/images/1_bg-1024x275.png" alt="1_bg-1024x275" data-fullwidthcentering="true"></div>

                <div class="tp-caption sfb start" data-x="146" data-y="-11" data-speed="300" data-start="600" data-easing="easeOutExpo"><img src="<?php echo SKIN_PATH?>default/plugins/revolslider/images/circuit-tree_03.png" alt="Thiết kế web Trí Tuệ Việt_Image 11"></div>

                <div class="tp-caption lft stb start" data-x="339" data-y="67" data-speed="300" data-start="1100" data-easing="easeOutExpo" data-end="5400" data-endspeed="300"><img src="<?php echo SKIN_PATH?>default/plugins/revolslider/images/laptop_03.png" alt="Thiết kế web Trí Tuệ Việt_Image 12"></div>

                <div class="tp-caption lft start" data-x="752" data-y="9" data-speed="300" data-start="8000" data-easing="easeOutExpo"><img src="<?php echo SKIN_PATH?>default/plugins/revolslider/images/phone_03.png" alt="Thiết kế web Trí Tuệ Việt_Image 14"></div>

                <div class="tp-caption lft start" data-x="405" data-y="196" data-speed="300" data-start="8500" data-easing="easeOutExpo"><img src="<?php echo SKIN_PATH?>default/plugins/revolslider/images/phone_06.png" alt="Thiết kế web Trí Tuệ Việt_Image 4"></div>

                <div class="tp-caption medium_text lfl start" data-x="36" data-y="191" data-speed="300" data-start="1400" data-easing="easeOutExpo"><span style="color:#3b372d; font-weight:bold;">RESPONSIVE</span></div>

                <div class="tp-caption medium_text lfl start" data-x="173" data-y="191" data-speed="300" data-start="1000" data-easing="easeOutExpo"><span style="color:#3b372d; font-weight:bold;">DESIGN </span></div>

                <div class="tp-caption large_text lfl start" data-x="16" data-y="120" data-speed="300" data-start="500" data-easing="easeOutExpo"><span style="color:orange; font-weight:bold;font-family: Arial;">WEBSITE ĐẸP</span></div>

                <div class="tp-caption lft stb start" data-x="473" data-y="18" data-speed="300" data-start="5500" data-easing="easeOutExpo" data-end="7900" data-endspeed="300"><img src="<?php echo SKIN_PATH?>default/plugins/revolslider/images/tablet_03.png" alt="Thiết kế web Trí Tuệ Việt_Image 12"></div>

                <div class="tp-caption lft stb start" data-x="632" data-y="47" data-speed="300" data-start="6000" data-easing="easeOutExpo" data-end="7900" data-endspeed="300"><img src="<?php echo SKIN_PATH?>default/plugins/revolslider/images/tablet_02_03.png" alt="Thiết kế web Trí Tuệ Việt_Image 13"></div>

                <div class="tp-caption medium_text fade start" data-x="23" data-y="237" data-speed="300" data-start="1600" data-easing="easeOutExpo">Giao diện reponsive design</div>

                <div class="tp-caption medium_text fade start" data-x="-25" data-y="273" data-speed="300" data-start="2000" data-easing="easeOutExpo">thích hợp với mọi loại thiết bị di động</div>
            </li>
            <li style="visibility: visible; left: 0px; top: 0px; z-index: 18; opacity: 0;" data-transition="slideright" data-slotamount="7">
                <div class="slotholder"><img style="width: 1601.16px; height: 430px; position: absolute; left: -7px; top: 0px; opacity: 0;" class="defaultimg" src="<?php echo SKIN_PATH?>default/plugins/revolslider/images/1_bg-1024x275.png" alt="1_bg-1024x275" data-fullwidthcentering="true"></div>

                <div style="top: 450px;" class="tp-caption lfb start" data-x="7" data-y="77" data-speed="300" data-start="900" data-easing="easeOutExpo"><img src="<?php echo SKIN_PATH?>default/plugins/revolslider/images/screens_03.png" alt="Thiết kế web Trí Tuệ Việt_Image 7"></div>

                <div style="opacity: 0;" class="tp-caption fade start" data-x="93" data-y="10" data-speed="300" data-start="1300" data-easing="easeOutExpo"><img src="<?php echo SKIN_PATH?>default/plugins/revolslider/images/screens_06.png" alt="Thiết kế web Trí Tuệ Việt_Image 9"></div>

                <div style="top: 450px;" class="tp-caption lfb start" data-x="199" data-y="108" data-speed="300" data-start="2000" data-easing="easeOutExpo"><img src="<?php echo SKIN_PATH?>default/plugins/revolslider/images/screens_09.png" alt="Thiết kế web Trí Tuệ Việt_Image 10"></div>

                <div style="left: 1607px;" class="tp-caption large_text lfr start" data-x="610" data-y="99" data-speed="600" data-start="2700" data-easing="easeOutExpo"><span style="color:orange;">DỄ QUẢN TRỊ</span></div>

                <div style="left: 1607px;" class="tp-caption medium_text lfr start" data-x="608" data-y="161" data-speed="600" data-start="3000" data-easing="easeOutExpo">TRONG 1 GIỜ</div>

                <div style="" class="tp-caption noshadow sfb start" data-x="608" data-y="197" data-speed="600" data-start="3300" data-easing="easeOutExpo">
                    Phần quản trị admin của GinTech được thiết kế định hướng<br>
                    tới sự đơn giản cho người sử dụng.Thân thiện, dễ hiểu, nhưng<br> vẫn đầy đủ chức năng, đó là tiêu chí hàng đầu của chúng tôi.<br>Bạn có thể thêm, bớt hoặc cập nhật sản phẩm một cách nhanh<br> chóng. Đăng một bài viết, quản lý bình luận, quản lý tin nhắn hay<br> thông tin khách hàng, … tất cả mọi việc, quản trị một website<br> thương mại điện tử không còn gì có thể đơn giản hơn thế.
                </div>
            </li>
        </ul>
        <div style="display: none;" class="tp-loader"></div><div class="tp-bannertimer" style="visibility: hidden; width: 97.8416%;"></div></div>
    <div style="visibility: visible; position: absolute; left: 0px; top: 215px; opacity: 1;" class="tp-leftarrow tparrows round-old large"></div><div style="visibility: visible; position: absolute; left: 1547px; top: 215px; opacity: 1;" class="tp-rightarrow tparrows round-old large"></div>
</div>

<script type="text/javascript">

    var tpj=jQuery;
				
    tpj.noConflict();
								
    var revapi1;
				
    tpj(document).ready(function() {
				
        if (tpj.fn.cssOriginal != undefined)
            tpj.fn.css = tpj.fn.cssOriginal;
				
        if(tpj('#rev_slider_1_1').revolution == undefined)
            revslider_showDoubleJqueryError('#rev_slider_1_1');
        else
            revapi1 = tpj('#rev_slider_1_1').show().revolution(
        {
            delay:9000,
            startwidth:1000,
            startheight:435,
            hideThumbs:50,
						
            thumbWidth:100,
            thumbHeight:50,
            thumbAmount:3,
						
            navigationType:"none",
            navigationArrows:"verticalcentered",
            navigationStyle:"round-old",
						
            touchenabled:"on",
            onHoverStop:"on",
						
            navOffsetHorizontal:0,
            navOffsetVertical:20,
						
            shadow:0,
            fullWidth:"on",

            stopLoop:"off",
            stopAfterLoops:-1,
            stopAtSlide:-1,

            shuffle:"off",
						
            hideSliderAtLimit:0,
            hideCaptionAtLimit:0,
            hideAllCaptionAtLilmit:0					});
				
    });	//ready
				
</script>
<!-- END SLIDER -->
<span class="wpsr_floatbts_anchor" data-offset="25"></span>
</div>