<?php $this->block("unslider") ?>
<section class="main_content">
    <section class="content">
        <section class="column_left fl">
            <header>
                Liên hệ
            </header>                 
            <section class="fl cateL">
                 Cảm ơn bạn đã gửi thông tin liên hệ. Chúng tôi sẽ phản hồi lại tron thời gian sớm nhất.
            </section>            
        </section>        
        <section class="sidebar fl">
            <?php echo $this->block('category'); ?>
        </section>           
    </section>
</section>