<section class="main_content">                                        
    <section class="content">
        <section class="column_left fl">
            <header>
                <?php echo $categoryInfo['title'];?>
                <div class="date_time"><?php /* $publicTime = new DateTime($product['public_time']); echo date_format($publicTime, 'g:i A');?> Ngày <?php echo date_format($publicTime, 'd/m/Y');*/?></div>
            </header>
            <div class="news_item">                
                <?php echo $product['pro_detail'];?>
            </div>                    
        </section>
        <section class="sidebar fl">
            <?php echo $this->block('category'); ?>
        </section>              
    </section>
</section>    
